version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./dev/django.Dockerfile
    command: ["./manage.py", "runserver", "0.0.0.0:8000"]
    # Log printing via Rich is enhanced by a TTY
    tty: true
    env_file: ./dev/.env.docker-compose
    volumes:
      - .:/opt/django-project
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbitmq
      - minio

  celery:
    build:
      context: .
      dockerfile: ./dev/django.Dockerfile
    command: [
      "celery",
      "--app", "shapeworks_cloud.celery",
      "worker",
      "--loglevel", "INFO",
      "--without-heartbeat"
    ]
    # Docker Compose does not set the TTY width, which causes Celery errors
    tty: false
    env_file: ./dev/.env.docker-compose
    volumes:
      - .:/opt/django-project
    depends_on:
      - postgres
      - rabbitmq
      - minio

  yarn:
    build:
      context: .
      dockerfile: ./dev/yarn.Dockerfile
    command: ["yarn", "serve"]
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - VUE_APP_OAUTH_CLIENT_ID=cBmD6D6F2YAmMWHNQZFPUr4OpaXVpW5w4Thod6Kj
      - VUE_APP_API_ROOT=http://localhost:8000/
      - VUE_APP_OAUTH_API_ROOT=http://localhost:8000/oauth/
    volumes:
      - ./web/shapeworks:/app/server
    working_dir: /app/server
    ports:
      - 8081:8080
