# Generated by Django 3.0.9 on 2021-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dataset_groomed_segmentation_shapemodel_shapemodelblob'),
    ]

    operations = [
        migrations.AddField(
            model_name='groomed',
            name='chirality',
            field=models.CharField(
                blank=True,
                choices=[('', ''), ('L', 'Left'), ('R', 'Right')],
                default='',
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name='groomed',
            name='extension',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', ''),
                    ('nrrd', 'nrrd'),
                    ('vtk', 'vtk'),
                    ('ply', 'ply'),
                    ('particles', 'particles'),
                ],
                default='',
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name='groomed',
            name='grooming_steps',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='groomed',
            name='particle_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', ''),
                    ('local', 'local'),
                    ('world', 'world'),
                    ('wptsFeatures', 'wptsFeatures'),
                ],
                default='',
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name='particles',
            name='chirality',
            field=models.CharField(
                blank=True,
                choices=[('', ''), ('L', 'Left'), ('R', 'Right')],
                default='',
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name='particles',
            name='extension',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', ''),
                    ('nrrd', 'nrrd'),
                    ('vtk', 'vtk'),
                    ('ply', 'ply'),
                    ('particles', 'particles'),
                ],
                default='',
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name='particles',
            name='grooming_steps',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='particles',
            name='particle_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', ''),
                    ('local', 'local'),
                    ('world', 'world'),
                    ('wptsFeatures', 'wptsFeatures'),
                ],
                default='',
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='chirality',
            field=models.CharField(
                blank=True,
                choices=[('', ''), ('L', 'Left'), ('R', 'Right')],
                default='',
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='extension',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', ''),
                    ('nrrd', 'nrrd'),
                    ('vtk', 'vtk'),
                    ('ply', 'ply'),
                    ('particles', 'particles'),
                ],
                default='',
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='grooming_steps',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='particle_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', ''),
                    ('local', 'local'),
                    ('world', 'world'),
                    ('wptsFeatures', 'wptsFeatures'),
                ],
                default='',
                max_length=12,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='groomed',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='particles',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='segmentation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='groomed',
            constraint=models.UniqueConstraint(
                fields=(
                    'subject',
                    'particle_type',
                    'chirality',
                    'extension',
                    'grooming_steps',
                    'dataset',
                ),
                name='unique_groomed',
            ),
        ),
        migrations.AddConstraint(
            model_name='particles',
            constraint=models.UniqueConstraint(
                fields=(
                    'subject',
                    'particle_type',
                    'chirality',
                    'extension',
                    'grooming_steps',
                    'shape_model',
                ),
                name='unique_particles',
            ),
        ),
        migrations.AddConstraint(
            model_name='segmentation',
            constraint=models.UniqueConstraint(
                fields=(
                    'subject',
                    'particle_type',
                    'chirality',
                    'extension',
                    'grooming_steps',
                    'dataset',
                ),
                name='unique_segmentation',
            ),
        ),
    ]
