# Generated by Django 3.0.9 on 2021-02-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210113_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapemodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
