# Generated by Django 3.2.9 on 2021-11-08 16:47

from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_alter_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesh',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('file', s3_file_field.fields.S3FileField()),
                ('anatomy_type', models.CharField(max_length=255)),
                (
                    'subject',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='meshes',
                        to='core.subject',
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='optimizedparticles',
            name='groomed_segmentation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='core.groomedsegmentation',
            ),
        ),
        migrations.CreateModel(
            name='GroomedMesh',
            fields=[
                ('file', s3_file_field.fields.S3FileField()),
                ('pre_cropping', s3_file_field.fields.S3FileField(null=True)),
                ('pre_alignment', s3_file_field.fields.S3FileField(null=True)),
                (
                    'mesh',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='groomed',
                        serialize=False,
                        to='core.mesh',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='groomed_meshes',
                        to='core.project',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='optimizedparticles',
            name='groomed_mesh',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='core.groomedmesh',
            ),
        ),
    ]
