# Generated by Django 3.2.13 on 2022-04-28 17:53

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dataset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizedparticles',
            name='constraints',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
    ]
