# Generated by Django 3.2.13 on 2022-05-17 00:28

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_optimizedparticles_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groomedmesh',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='groomedsegmentation',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='mesh',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='optimizedparticles',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='optimizedpcamodel',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='optimizedshapemodel',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='optimizedsurfacereconstruction',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='optimizedsurfacereconstructionmeta',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='segmentation',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='groomedmesh',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groomedmesh',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='groomedsegmentation',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groomedsegmentation',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='image',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='mesh',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesh',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='optimizedparticles',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optimizedparticles',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='optimizedpcamodel',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optimizedpcamodel',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='optimizedshapemodel',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optimizedshapemodel',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='optimizedsurfacereconstruction',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optimizedsurfacereconstruction',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='optimizedsurfacereconstructionmeta',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optimizedsurfacereconstructionmeta',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segmentation',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name='modified'
            ),
        ),
    ]
