# Generated by Django 3.2.15 on 2022-09-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_analysis_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizedshapemodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='optimizedsurfacereconstruction',
            name='particles',
        ),
        migrations.RemoveField(
            model_name='optimizedsurfacereconstructionmeta',
            name='shape_model',
        ),
        migrations.RemoveField(
            model_name='optimizedparticles',
            name='shape_model',
        ),
        migrations.AddField(
            model_name='optimizedparticles',
            name='project',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='core.project'
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OptimizedPCAModel',
        ),
        migrations.DeleteModel(
            name='OptimizedShapeModel',
        ),
        migrations.DeleteModel(
            name='OptimizedSurfaceReconstruction',
        ),
        migrations.DeleteModel(
            name='OptimizedSurfaceReconstructionMeta',
        ),
    ]
