# Generated by Django 3.2.16 on 2022-10-13 12:02

from django.db import migrations, models
import django.db.models.deletion

# remove pointers to previous groomed shape primary keys
# remove primary key attribute from original shape pointer
# add new autofields to groomed shapes
# add back pointers to groomed shapes on particle objects


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_remove_redundant_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizedparticles',
            name='groomed_mesh',
        ),
        migrations.RemoveField(
            model_name='optimizedparticles',
            name='groomed_segmentation',
        ),
        migrations.AlterField(
            model_name='groomedmesh',
            name='mesh',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='groomed', to='core.mesh'
            ),
        ),
        migrations.AlterField(
            model_name='groomedsegmentation',
            name='segmentation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='groomed',
                to='core.segmentation',
            ),
        ),
        migrations.AddField(
            model_name='groomedmesh',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groomedsegmentation',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optimizedparticles',
            name='groomed_mesh',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='core.groomedmesh',
            ),
        ),
        migrations.AddField(
            model_name='optimizedparticles',
            name='groomed_segmentation',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='core.groomedsegmentation',
            ),
        ),
    ]
