# Generated by Django 3.2.16 on 2022-10-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_groomed_shapes_pks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_cached_analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cachedanalysis'),
        ),
    ]
