# Generated by Django 3.2.16 on 2022-11-07 19:10

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_reconstructed_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='thumbnail',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
    ]
