# Generated by Django 3.2.16 on 2022-11-18 18:16

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizedparticles',
            name='constraints',
        ),
        migrations.AlterField(
            model_name='optimizedparticles',
            name='transform',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.CreateModel(
            name='Landmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', s3_file_field.fields.S3FileField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='core.subject')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', s3_file_field.fields.S3FileField()),
                ('anatomy_type', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='core.subject')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Constraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', s3_file_field.fields.S3FileField()),
                ('optimized_particles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='core.optimizedparticles')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='core.subject')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
