# Generated by Django 3.2.16 on 2022-12-12 17:24

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_contours_landmarks_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedanalysismodepca',
            name='particles',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
    ]
