# Generated by Django 3.2.16 on 2022-12-19 18:48

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_constraints_no_particles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedanalysis',
            name='mean_particles',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
    ]
