# Generated by Django 3.2.16 on 2023-01-27 14:35

import uuid

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_private_datasets'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                (
                    'task_id',
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                ('name', models.CharField(max_length=255)),
                ('error', models.CharField(max_length=255)),
                ('percent_complete', models.IntegerField(default=0)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
