# Generated by Django 3.2.17 on 2023-02-17 19:48

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0023_task_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizedparticles',
            name='local',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='optimizedparticles',
            name='world',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
    ]
