# Generated by Django 3.2.17 on 2023-02-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0024_world_local_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
