# Generated by Django 3.2.17 on 2023-03-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_subject_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='group',
        ),
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
