# Generated by Django 3.2.18 on 2023-03-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0026_subject_multi_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedanalysis',
            name='groups',
            field=models.JSONField(null=True),
        ),
    ]
