# Generated by Django 3.2.17 on 2023-03-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0026_subject_multi_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskprogress',
            name='task_id',
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='abort',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
            preserve_default=False,
        ),
    ]
