# Generated by Django 3.2.17 on 2023-03-14 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0026_subject_multi_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
            preserve_default=False,
        ),
    ]
