# Generated by Django 3.2.18 on 2023-03-09 19:32

from django.db import migrations, models
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0027_Analysis_Groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedAnalysisGroup',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('file', s3_file_field.fields.S3FileField()),
                ('particles', s3_file_field.fields.S3FileField(null=True)),
            ],
        ),
    ]
