# Generated by Django 3.2.18 on 2023-03-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0028_Analysis_Groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedanalysisgroup',
            name='group1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cachedanalysisgroup',
            name='group2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cachedanalysisgroup',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
