# Generated by Django 3.2.18 on 2023-03-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0029_Analysis_Groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedanalysisgroup',
            name='ratio',
            field=models.FloatField(default=0.0),
        ),
    ]
