# Generated by Django 3.2.18 on 2023-04-05 22:47

from django.db import migrations, models
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0029_anatomy_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedAnalysisGroup',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(default='', max_length=255)),
                ('group1', models.CharField(default='', max_length=255)),
                ('group2', models.CharField(default='', max_length=255)),
                ('ratio', models.FloatField(default=0.0)),
                ('file', s3_file_field.fields.S3FileField()),
                ('particles', s3_file_field.fields.S3FileField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cachedanalysis',
            name='groups',
            field=models.ManyToManyField(to='core.CachedAnalysisGroup'),
        ),
    ]
