# Generated by Django 3.2.18 on 2023-04-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0030_Analysis_Groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedanalysis',
            name='groups',
            field=models.ManyToManyField(blank=True, to='core.CachedAnalysisGroup'),
        ),
    ]
