# Generated by Django 3.2.18 on 2023-03-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0032_cachedanalysis_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedanalysis',
            name='groups',
            field=models.ManyToManyField(to='core.CachedAnalysisGroup'),
        ),
    ]
