# Generated by Django 3.2.18 on 2023-03-10 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0033_alter_cachedanalysis_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedanalysisgroup',
            old_name='file',
            new_name='mesh',
        ),
    ]
