# Generated by Django 3.2.18 on 2023-03-10 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0034_rename_file_cachedanalysisgroup_mesh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedanalysisgroup',
            old_name='mesh',
            new_name='file',
        ),
    ]
