# Generated by Django 3.2.21 on 2023-09-25 20:42

from django.db import migrations, models
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_protect_from_cascading_deletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedAnalysisMeanShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', s3_file_field.fields.S3FileField()),
                ('particles', s3_file_field.fields.S3FileField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cachedanalysis',
            name='mean_particles',
        ),
        migrations.RemoveField(
            model_name='cachedanalysis',
            name='mean_shape',
        ),
        migrations.AddField(
            model_name='cachedanalysis',
            name='mean_shapes',
            field=models.ManyToManyField(to='core.CachedAnalysisMeanShape'),
        ),
    ]
