# Generated by Django 3.2.18 on 2023-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0035_rename_mesh_cachedanalysisgroup_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedanalysisgroup',
            name='group1',
        ),
        migrations.RemoveField(
            model_name='cachedanalysisgroup',
            name='group2',
        ),
        migrations.AddField(
            model_name='cachedanalysisgroup',
            name='members',
            field=models.JSONField(default=[]),
        ),
    ]
