# Generated by Django 3.2.21 on 2023-11-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0036_analysis_multi_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraints',
            name='optimized_particles',
        ),
        migrations.AddField(
            model_name='constraints',
            name='project',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='constraints',
                to='core.project',
            ),
        ),
    ]
