# Generated by Django 3.2.18 on 2023-03-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0036_auto_20230316_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedanalysisgroup',
            name='members',
            field=models.JSONField(default=list),
        ),
    ]
