# Generated by Django 3.2.24 on 2024-02-23 19:00

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_analysis_multi_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedDeepSSMAugPair',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('mesh', s3_file_field.fields.S3FileField()),
                ('particles', s3_file_field.fields.S3FileField()),
            ],
        ),
        migrations.CreateModel(
            name='CachedDeepSSMTestingData',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('mean_distance', models.FloatField()),
                ('mesh', s3_file_field.fields.S3FileField()),
                ('particles', s3_file_field.fields.S3FileField()),
            ],
        ),
        migrations.CreateModel(
            name='CachedDeepSSMTraining',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('visualization', s3_file_field.fields.S3FileField()),
                ('data_table', s3_file_field.fields.S3FileField()),
            ],
        ),
        migrations.CreateModel(
            name='CachedDeepSSMTesting',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('data', models.ManyToManyField(to='core.CachedDeepSSMTestingData')),
            ],
        ),
        migrations.CreateModel(
            name='CachedDeepSSMAug',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('visualization', s3_file_field.fields.S3FileField()),
                ('pairs', models.ManyToManyField(to='core.CachedDeepSSMAugPair')),
            ],
        ),
        migrations.CreateModel(
            name='CachedDeepSSM',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                (
                    'augmentation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.cacheddeepssmaug'
                    ),
                ),
                (
                    'testing',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.cacheddeepssmtesting',
                    ),
                ),
                (
                    'training',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.cacheddeepssmtraining',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='last_cached_deepssm',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cacheddeepssm'
            ),
        ),
    ]
