# Generated by Django 3.2.25 on 2024-03-15 19:54

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_deepssm_phase_2_and_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedDeepSSMResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cacheddeepssmaug',
            name='pairs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_cached_deepssm',
        ),
        migrations.AddField(
            model_name='cacheddeepssmaug',
            name='pair',
            field=models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, to='core.cacheddeepssmaugpair'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cacheddeepssmaug',
            name='project',
            field=models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, related_name='deepssm_aug', to='core.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cacheddeepssmaugpair',
            name='subject',
            field=models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cacheddeepssmtesting',
            name='project',
            field=models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, related_name='deepssm_testing', to='core.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cacheddeepssmtestingdata',
            name='subject',
            field=models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cacheddeepssmtraining',
            name='project',
            field=models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, related_name='deepssm_training', to='core.project'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cacheddeepssmtesting',
            name='data',
        ),
        migrations.AddField(
            model_name='cacheddeepssmtesting',
            name='data',
            field=models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, to='core.cacheddeepssmtestingdata'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CachedDeepSSM',
        ),
        migrations.AddField(
            model_name='cacheddeepssmresult',
            name='augmentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cacheddeepssmaug'),
        ),
        migrations.AddField(
            model_name='cacheddeepssmresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_deepssm', to='core.project'),
        ),
        migrations.AddField(
            model_name='cacheddeepssmresult',
            name='testing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cacheddeepssmtesting'),
        ),
        migrations.AddField(
            model_name='cacheddeepssmresult',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cacheddeepssmtraining'),
        ),
    ]
