# Generated by Django 3.2.18 on 2023-03-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0038_rename_members_cachedanalysisgroup_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedanalysis',
            name='groups',
            field=models.ManyToManyField(null=True, to='core.CachedAnalysisGroup'),
        ),
        migrations.AlterField(
            model_name='cachedanalysisgroup',
            name='groups',
            field=models.JSONField(default=''),
        ),
    ]
