# Generated by Django 3.2.18 on 2023-03-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0039_auto_20230317_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedanalysis',
            name='groups',
            field=models.ManyToManyField(to='core.CachedAnalysisGroup'),
        ),
        migrations.AlterField(
            model_name='cachedanalysisgroup',
            name='groups',
            field=models.JSONField(default=list),
        ),
    ]
