# Generated by Django 3.2.23 on 2023-12-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0039_partial_deepssm_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedmodel',
            name='ft_predictions',
            field=models.ManyToManyField(
                blank=True, related_name='ft_predictions', to='core.CachedPrediction'
            ),
        ),
        migrations.AlterField(
            model_name='cachedmodel',
            name='pca_predictions',
            field=models.ManyToManyField(
                blank=True, related_name='pca_predictions', to='core.CachedPrediction'
            ),
        ),
    ]
