# Generated by Django 3.2.25 on 2024-04-12 23:05

from django.db import migrations, models
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_deepssm_phase2_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepssmtrainingpair',
            name='vtk',
        ),
        migrations.AddField(
            model_name='deepssmaugpair',
            name='image',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AddField(
            model_name='deepssmtrainingimage',
            name='index',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deepssmtrainingpair',
            name='mesh',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmaugpair',
            name='mesh',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmaugpair',
            name='particles',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmaugpair',
            name='sample_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmresult',
            name='aug_total_data',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmresult',
            name='aug_visualization',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmresult',
            name='testing_distances',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmresult',
            name='training_data_table',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmresult',
            name='training_visualization',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmresult',
            name='training_visualization_ft',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmtestingdata',
            name='image_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deepssmtestingdata',
            name='image_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deepssmtestingdata',
            name='mesh',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmtestingdata',
            name='particles',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmtrainingimage',
            name='image',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmtrainingpair',
            name='example_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deepssmtrainingpair',
            name='index',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deepssmtrainingpair',
            name='particles',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
        migrations.AlterField(
            model_name='deepssmtrainingpair',
            name='scalar',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
    ]
