# Generated by Django 3.2.23 on 2023-12-18 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0040_partial_deepssm_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cachedaugmentation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cachedaugmentationpair',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cacheddataloaders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cachedexample',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cachedmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cachedmodelexamples',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cachedprediction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cachedtensors',
            options={},
        ),
        migrations.RemoveField(
            model_name='cachedaugmentation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cachedaugmentation',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='cachedaugmentationpair',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cachedaugmentationpair',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='cacheddataloaders',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cacheddataloaders',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='cachedexample',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cachedexample',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='cachedmodel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cachedmodel',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='cachedmodelexamples',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cachedmodelexamples',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='cachedprediction',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cachedprediction',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='cachedtensors',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cachedtensors',
            name='modified',
        ),
    ]
