# Generated by Django 3.2.25 on 2024-04-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_deepssm_ui_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogress',
            name='form_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
