# Generated by Django 3.2.18 on 2023-03-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0040_auto_20230317_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedanalysisgroup',
            name='groups',
        ),
        migrations.AddField(
            model_name='cachedanalysisgroup',
            name='group1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cachedanalysisgroup',
            name='group2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
